services:
  frontend:
    build: ./frontend
    container_name: frontend_conatiner
    ports:
      - 3000:5173
    volumes:
      - ./frontend:/usr/app/frontend
      - /usr/app/frontend/node_modules
  backend:
    build: ./backend
    container_name: backend_conatiner
    ports:
      - 4000:3000
    volumes:
      - ./backend:/usr/app/backend
      - /usr/app/backend/node_modules
    links: 
      - "mongodb"
  nginx:
    image: nginx
    container_name: nginx_container
    volumes:
      - ./ngix:/etc/nginx/conf.d
    ports:
      - 5000:80
    networks:
      - red
  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - 27017:27017

networks:
  red: