services:
  frontend:
    stdin_open: true
    build: 
      context: ./frontend
      args:
        MY_VAR: ${SUDO_PASSWORD}
    container_name: frontend_container
    ports:
      - 3000:5173
    volumes:
      - ./frontend:/usr/app/frontend
      - /usr/app/frontend/node_modules
    networks:
      - red
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - 4000:3001
    volumes:
      - ./backend:/usr/app/backend
      - /usr/app/backend/node_modules
    links: 
      - "mongodb"
    networks:
      - red
  nginx:
    image: nginx
    container_name: nginx_container
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 5000:80
    networks:
      - red
  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - 27017:27017

networks:
  red: