version: '3.9'
services:
  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx_container
    ports:
      - 8000:8000
    networks:
      - redFrontend
      - redBackend
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../nginx/nginx_static_pages:/usr/share/nginx/html/nginx_static_pages