name: App CI CD

on:
   push:
      branches: ["deploy"]

jobs:
  build:
    runs-on: self-hosted
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker Compose
        run: docker compose build
      - name: Up the Docker Compose
        run: docker compose up -d
